### ISSUE TITLE
crypto.createDecipher is deprecated

### ISSUE THREAD

**Issue by suzushin54** [tosaka-n/ts-dash#15]
Hi, I've tried this tool but there seems to be a deprecated module.
I'll leave a log..

```bash
$ ts-dash in
status to in	
(node:97936) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipher.final (internal/crypto/cipher.js:173:29)
    at exports.decrypt (/Users/shinichiro.suzuki/work/ts-dash/encrypt.js:13:19)
    at init (/Users/shinichiro.suzuki/work/ts-dash/index.js:144:16)
    at Command.handler (/Users/shinichiro.suzuki/work/ts-dash/index.js:19:11)
    at Command.listener (/Users/shinichiro.suzuki/work/ts-dash/node_modules/commander/index.js:291:8)
    at Command.emit (events.js:193:13)
    at Command.parseArgs (/Users/shinichiro.suzuki/work/ts-dash/node_modules/commander/index.js:672:12)
    at Command.parse (/Users/shinichiro.suzuki/work/ts-dash/node_modules/commander/index.js:459:21)
    at Object.<anonymous> (/Users/shinichiro.suzuki/work/ts-dash/index.js:83:9)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
```

```bash
$ node -v
v11.14.0
```

thanks.

**Comment by tosaka-n** [comment]
thank you for your reporting.
I knew that issue.
So, I fixed that https://github.com/tosaka-n/ts-dash/pull/16.
Could you try it?
